packages:
  - apps/*
  - packages/*
  - harness-bundle

overrides:
  "@codemirror/lint": 6.9.5

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@google/genai": true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

patchedDependencies:
  "@deepseek-ai/dsh-host-webserver@0.1.1-rc.2": patches/@deepseek-ai__dsh-host-webserver@0.1.1-rc.2.patch
