import { validateModuleGraph, type ModuleManifest } from "@workagent/contracts";

export const RUNTIME_MODULES = [
  {
    id: "model-access",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["model.catalog", "model.authorization"],
    dependencies: [],
    configSchema: "workagent://schemas/model-access/v1",
    dataOwner: "employee SID model grants and public catalog projection",
    healthCheck: "/v1/models",
  },
  {
    id: "credential-broker",
    version: "1.0.0",
    layer: "adapter",
    required: true,
    capabilities: ["credential.status"],
    dependencies: [],
    configSchema: "workagent://schemas/credential-broker/v1",
    dataOwner: "employee SID native credential directories and references",
    healthCheck: "/v1/credentials",
  },
  {
    id: "engine-registry",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["engine.catalog", "engine.status", "engine.capabilities"],
    dependencies: [
      { id: "model-access", contract: "ModelCatalogPort/v1" },
      { id: "credential-broker", contract: "CredentialBrokerPort/v1" },
    ],
    configSchema: "workagent://schemas/engine-registry/v1",
    dataOwner: "native engine configuration under the employee SID",
    healthCheck: "/v1/engines",
  },
  {
    id: "skill-runtime",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["skill.catalog", "skill.state", "skill.binding"],
    dependencies: [],
    configSchema: "workagent://schemas/skill-runtime/v1",
    dataOwner: "employee SID private installed skill catalog",
    healthCheck: "/v1/skills",
  },
  {
    id: "mcp-runtime",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["mcp.catalog", "mcp.crud", "mcp.projection"],
    dependencies: [
      { id: "credential-broker", contract: "CredentialBrokerPort/v1" },
    ],
    configSchema: "workagent://schemas/mcp-runtime/v1",
    dataOwner: "employee SID private MCP catalog and bindings",
    healthCheck: "/v1/mcp-servers",
  },
  {
    id: "preset-runtime",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["preset.crud", "preset.snapshot", "preset.binding"],
    dependencies: [
      { id: "engine-registry", contract: "EngineCatalogPort/v1" },
      { id: "model-access", contract: "ModelAuthorizationPort/v1" },
      { id: "skill-runtime", contract: "SkillCatalogPort/v1" },
      { id: "mcp-runtime", contract: "McpCatalogPort/v1" },
    ],
    configSchema: "workagent://schemas/preset-runtime/v1",
    dataOwner: "employee SID private preset definitions and immutable versions",
    healthCheck: "/v1/presets",
  },
  {
    id: "workspace-runtime",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: [
      "workspace.files",
      "workspace.attachments",
      "workspace.artifacts",
    ],
    dependencies: [],
    configSchema: "workagent://schemas/workspace-runtime/v1",
    dataOwner: "employee SID private workspace root and asset index",
    healthCheck: "/v1/workspaces",
  },
  {
    id: "personal-work",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["session.lifecycle", "session.messages", "session.events"],
    dependencies: [
      { id: "engine-registry", contract: "AgentEngine/v1" },
      { id: "preset-runtime", contract: "PresetRuntimePort/v1" },
      { id: "workspace-runtime", contract: "WorkspaceBinding/v1" },
    ],
    configSchema: "workagent://schemas/personal-work/v1",
    dataOwner: "employee SID private session index and message logs",
    healthCheck: "/v1/sessions",
  },
  {
    id: "approval-bridge",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: [
      "interaction.pending",
      "interaction.respond",
      "interaction.recover",
    ],
    dependencies: [
      { id: "personal-work", contract: "SessionInteractionSink/v1" },
    ],
    configSchema: "workagent://schemas/approval-bridge/v1",
    dataOwner: "employee SID private pending interaction index",
    healthCheck: "/v1/interactions",
  },
  {
    id: "automation",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: [
      "automation.crud",
      "automation.schedule",
      "automation.run",
      "automation.history",
    ],
    dependencies: [
      { id: "personal-work", contract: "AutomationRunnerPort/v1" },
      { id: "preset-runtime", contract: "PresetRuntimePort/v1" },
      { id: "workspace-runtime", contract: "WorkspaceBinding/v1" },
    ],
    configSchema: "workagent://schemas/automation/v1",
    dataOwner: "employee SID private automation definitions and run history",
    healthCheck: "/v1/automations",
  },
  {
    id: "ai-team",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: [
      "team.crud",
      "team.members",
      "team.tasks",
      "team.mailbox",
      "team.events",
    ],
    dependencies: [
      { id: "personal-work", contract: "TeamRunnerPort/v1" },
      { id: "preset-runtime", contract: "PresetRuntimePort/v1" },
      { id: "workspace-runtime", contract: "WorkspaceBinding/v1" },
    ],
    configSchema: "workagent://schemas/ai-team/v1",
    dataOwner: "employee SID private teams, tasks, mailbox, and run history",
    healthCheck: "/v1/teams",
  },
  {
    id: "shared-turn",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["shared.turn.run", "shared.turn.cancel"],
    dependencies: [
      { id: "engine-registry", contract: "AgentEngine/v1" },
      { id: "preset-runtime", contract: "PresetRuntimePort/v1" },
    ],
    configSchema: "workagent://schemas/shared-turn/v1",
    dataOwner: "owner SID private shared engine sessions",
    healthCheck: "/v1/shared-turns",
  },
  {
    id: "runtime-api",
    version: "1.0.0",
    layer: "runtime",
    required: true,
    capabilities: ["runtime.health", "runtime.proxy-contract"],
    dependencies: [
      { id: "personal-work", contract: "PersonalWorkPort/v1" },
      { id: "approval-bridge", contract: "ApprovalPort/v1" },
      { id: "automation", contract: "AutomationPort/v1" },
      { id: "ai-team", contract: "TeamPort/v1" },
      { id: "shared-turn", contract: "SharedTurnRunner/v1" },
      { id: "im-inbox", contract: "InboxPort/v1" },
    ],
    configSchema: "workagent://schemas/runtime-api/v1",
    dataOwner: "none; routing and DTO projection only",
    healthCheck: "/health",
  },
  {
    id: "im-inbox",
    version: "1.0.0",
    layer: "adapter",
    required: true,
    capabilities: ["im.receive", "im.deduplicate", "im.session-map"],
    dependencies: [{ id: "personal-work", contract: "InboxRunnerPort/v1" }],
    configSchema: "workagent://schemas/im-inbox/v1",
    dataOwner: "employee SID private IM delivery receipts and session mapping",
    healthCheck: "/v1/inbox/messages",
  },
] satisfies ModuleManifest[];

validateModuleGraph(RUNTIME_MODULES);
